### ISSUE TITLE
Publish package to conda-forge

### ISSUE THREAD

**Issue by mlshapiro** [contrailcirrus/pycontrails#27]
**Description**

Support install with `conda install pycontrails` on the conda-forge channel.

Should be fairly easy once published to pypi. See https://conda-forge.org/docs/maintainer/adding_pkgs.html

**Alternatives**

- Ignore conda for now

**Comment by mlshapiro** [comment]
According to https://stackoverflow.com/a/66539742 - Once we do this setup once, `conda-forge` will pull new releases from pypi

**Comment by mlshapiro** [comment]
Going to ignore this for now

**Comment by aeroevan** [comment]
For reference, a meta.yaml like this one works for building a conda package (generated using grayskull):
```
{% set name = "pycontrails" %}
{% set version = "0.49.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pycontrails-{{ version }}.tar.gz
  sha256: ddab48301d18200eb732a68d813c8241d039108a2872013deced2b4dcab2e5d1

build:
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python >=3.9
    - setuptools
    - setuptools-scm
    - wheel
    - cython
    - numpy
    - pip
  run:
    - python >=3.9
    - dask-core >=2022.3
    - overrides >=6.1
    - pandas >=1.4
    - scipy >=1.10
    - xarray >=2022.3
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pycontrails
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Python library for modeling aviation climate impacts
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
```
